# Only for local development!

# The PostgreSQL image
FROM postgres:16.2

# The database & user
ENV POSTGRES_DB gadgets
ENV POSTGRES_USER gadgets
ENV POSTGRES_PASSWORD gadgets

# Exposes the container's port for access from the host
EXPOSE 5432