spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-root.xml
    contexts: none
  data:
    web:
      pageable:
        max-page-size: 50
        # Automatically decrements the page in incoming requests, so that pagination starts from 1 for the client
        one-indexed-parameters: true
